#!/usr/bin/env ruby

def dependency_jars
  raw = `sbt "show compile:dependency-classpath"`
  raw.scan(%r{[a-zA-Z0-9./_-]+[.]jar})
end

def classpath
  $classpath ||= ("target/scala-2.9.1/classes:" + dependency_jars.join(":"))
end

def run_hadoop(command, job, input, output)
  system("scala -cp #{classpath} io.sizzling.hadoop.Tool #{job} #{command} #{input} #{output}")
end

def run_simple(job, input)
  system("scala -cp #{classpath} io.sizzling.simple.TextRunner #{job} < #{input} | sort")
end

command = ""

job = ARGV.shift
unless job =~ /[.]/
  job = "io.sizzling.examples." + job
end

input = ARGV.shift

if(ARGV.shift == "-hadoop")
  out1 = "#{input}.tmp1"
  out2 = "#{input}.tmp2"

  system("rm -rf #{out1}")
  system("rm -rf #{out2}")

  run_hadoop("io.sizzling.hadoop.TextInputCommand", job, input, out1)
  run_hadoop("io.sizzling.hadoop.OutputCommand", job, out1, out2)
  puts
  puts
  puts("cat #{out2}/*")
  system("cat #{out2}/*")
else
  run_simple(job, input)
end

